bower.json
config/assets/default.js
modules/core/client/app/config.js
modules/core/client/scss/components/file-browser.scss
modules/core/client/scss/components/misc.scss
modules/documents/client/components/doc-categories/doc-categories.js
modules/documents/client/components/doc-categories/doc-categories.modal.html
modules/documents/client/components/doc-categories/doc-categories.scss
modules/documents/client/directives/documents.manager.directive.js
modules/documents/client/directives/documents.manager.edit.directive.js
modules/documents/client/directives/documents.publish.confirm.directive.js
modules/documents/client/services/documents.upload.service.js
modules/documents/client/views/document-manager-edit.html
modules/documents/client/views/document-manager.html
modules/documents/server/controllers/core.document.controller.js
modules/documents/server/models/document.model.js

MEM-360 Document Manager [Doc Date Month Year display and required] (e.g., a document dated June 2015).
MEM-369 Use "Document Date" for sorting in document listing
MEM-376 Add more fields and adjustments in Doc Manager, for MEM. Copy clipboard, publish unpublish labels, remove API filter that removed Day from Document Date, natural sort on display name
MEM-390 MEM Document Manager: Modifications from Review

MEM Doc Manager updates and sync with EPIC

---

modules/core/client/scss/components/file-browser.scss
modules/core/client/scss/global/helpers.scss
modules/core/client/scss/global/mixins.scss
modules/documents/client/views/document-manager.html

Restructured the Document Info Panel metadata, style sheet clean-up

MEM-391 Document Info Panel Refactor

---

modules/core/client/scss/components/file-browser.scss
modules/documents/client/views/document-manager-link.html
modules/documents/client/views/document-manager-move.html
modules/documents/client/views/document-manager.html

Fixes / Refactoring the Breadcrumb component for the Document Manager Interface(s).

MEM-400 Document Manager UI Breadcrumb Updates

---

modules/core/client/scss/components/file-browser.scss
modules/documents/client/views/document-manager-link.html
modules/documents/client/views/document-manager.html

Fixed a few issues with hover states on row items in the document manager interface
- Fixed an issue where the 'Select All/None' column header had no hover state
- Added visual hover state for all row items

MEM-400 Minor Usability Improvements

---

modules/core/client/filters/core.filters.js
modules/documents/client/components/doc-categories/README.md
modules/documents/client/components/doc-categories/doc-categories.js
modules/documents/client/directives/documents.manager.directive.js
modules/documents/client/directives/documents.manager.edit.directive.js
modules/documents/client/directives/documents.publish.confirm.directive.js
modules/documents/client/views/document-manager-edit.html
modules/documents/client/views/document-manager.html
modules/documents/client/views/partials/modal-document-confirm-publish.html
modules/documents/server/models/document.model.js

Fields depend on which type of inspection report is the first category. 
Several adjustments to text labels.
Change category "Inspection Follow Up" to "Inspection Report Follow Up"
Document sorting on document date fixed. Works with Month Year dates.
Confirm publish dialog improved.
Merge Jer's changes, resolve conflicts, redo code as needed
Uploaded Date was showing dateAdded not dateUploaded. Fix to show uploaded if set otherwise date added.

MEM-413 add new fields to inspection report categories, 

---

modules/core/client/components/fn-filename/README.md
modules/core/client/components/fn-filename/index.js
modules/documents/client/controllers/documents.client.controllers.js
modules/documents/client/directives/documents.manager.directive.js
modules/documents/client/directives/documents.manager.edit.directive.js
modules/documents/client/directives/documents.manager.link.directive.js
modules/documents/client/directives/documents.manager.move.directive.js
modules/documents/client/views/document-manager-edit.html
modules/documents/client/views/document-manager.html
modules/documents/server/controllers/core.document.controller.js
modules/documents/server/models/document.model.js
modules/documents/server/routes/core.document.routes.js
scripts/etlDisplayName.js
scripts/etlHelper.js
scripts/etlPing.js

MEM-399 Document filename is used for download. Add filename validation component 
MEM-395 document filename and displayName ETL to populate. On download use the fileName

MEM-399, 395 Document filename.

---

modules/projects/client/controllers/projects.client.controllers.js

ngTable can accept a getData method (rather than just the data set) and in this getData we can perform the custom natural sort. In this method we also filter the data.

MEM-405 sort project page with natural sort order and preserve filtering

---

bower.json
config/assets/default.js
modules/collections/client/directives/collections.reorder.js
modules/collections/client/scss/collections.scss
modules/collections/client/views/collection-view.html
modules/collections/client/views/collections-reorder-content.html
modules/collections/client/views/modal-collections-reorder.html
modules/core/client/app/config.js

Working up to but not including actual database save

[dev] MEM-398-collection-ordering proof of concept. 

---

modules/projects/client/controllers/projects.client.controllers.js

Temporary back out "MEM-405 sort project page with natural sort order and preserve filtering"

---

modules/documents/client/directives/documents.manager.edit.directive.js

Temporary back out "MEM-415-fixFolderEdit. Folder's do not have file extensions"

---

modules/projects/client/controllers/projects.client.controllers.js

Putting back "Temporary back out "MEM-405 sort project page with natural sort order and preserve filtering""

---

modules/documents/client/directives/documents.manager.edit.directive.js

Putting back "Temporary back out "MEM-415-fixFolderEdit. Folder's do not have file extensions""

---

modules/core/client/views/menu.client.view.html
modules/documents/client/directives/documents.manager.move.directive.js

Just pulling over Usanth's changes

MEM-425 bring EPIC-996 EPIC-1074 to MEM

---

modules/documents/client/directives/documents.manager.directive.js

Porting logancodes fix from EPIC->MEM

EPIC-1065 - Fix multiple folder move functionality

---

modules/collections/client/directives/collections.reorder.js

Showing the existing sort order on the console, when the sorting dialog opens.  I'm mainly needing to trigger a new dev build.

[Dev] Collection ordering. Add a debug message to show sort order

---

modules/documents/client/components/doc-categories/doc-categories.js
modules/documents/server/models/document.model.js

Accept categories with sub-categories. Reject other categories and happen to include text: inspection report.
Needs testing on dev env.

[Dev] Fix inspection type calculation. 

---

modules/core/client/components/fn-filename/index.js
modules/documents/client/directives/documents.manager.directive.js
modules/documents/client/views/document-manager-edit.html
modules/documents/client/views/document-manager.html

MEM-415 Doc manager edit doc dialog no longer activates buttons when ENTER is pressed
Text changes. Default document sort order is now document date
MEM-422 fix case there are spaces at end of filename before file extension and handle the double validation that happens

[Dev] MEM-415, MEM-422 fix and improve doc manager

---

modules/core/client/components/fn-filename/index.js
modules/documents/client/directives/documents.manager.directive.js
modules/documents/client/views/document-manager-edit.html
modules/documents/client/views/document-manager.html

Prevent ENTER from activating buttons in doc edit dialog
Text changes. 
Default document sort order is now document date
MEM-422 fix case there are spaces at end of filename before file extension and handle the double validation that happens

MEM-415 Doc manager changes

---

bower.json
config/assets/default.js
modules/collections/client/config/collections.routes.js
modules/collections/client/directives/collections.reorder.js
modules/collections/client/scss/collections.scss
modules/collections/client/services/collections.client.services.js
modules/collections/client/views/collection-view.html
modules/collections/client/views/collections-reorder-content.html
modules/collections/client/views/modal-collections-reorder.html
modules/collections/server/controllers/collections.controller.js
modules/collections/server/routes/collections.routes.js
modules/core/client/app/config.js

Pop-out dialog lets users determine default sort order with drag and drop action.
Title instructs user.
Areas which trigger scroll are enlarged
Known display only issues with FF and IE accepted by BO. (The image of the dragged item is half size in FF and has too much transparency in IE.)

MEM-398-collection-ordering

---

modules/documents/client/directives/documents.manager.directive.js
modules/documents/client/directives/documents.manager.edit.directive.js
modules/documents/client/views/document-manager-edit.html
modules/folders/server/models/folder.model.js

Provide means to set the default sort order for folders to Date desc or Name desc.

Mem 460 default sorting

---

modules/collections/client/views/collection-view.html
modules/documents/client/components/doc-categories/doc-categories.js

Also fixed display of document date in collections.

MEM-458 and 439; Fix collection layout; add new doc category

---

modules/collections/client/scss/collections.scss
modules/collections/client/views/collection-edit.html
modules/collections/client/views/collection-view.html
modules/collections/client/views/collections-list.html
modules/core/client/scss/components/forms.scss
modules/core/client/scss/core.scss

Refactor / clean-up of the collections interface(s) and styling
Additional fixes
- Removed the majority of the form element styling out of core.scss into forms.scss
- Added status column to both main and other document components
- Fixed incorrect usage of title tag properties on various elements
- Fixed an issue where the side navigation project link would not render it's with on initial load.

MEM-486 - Collections UI Cleanup

---

modules/projects/server/models/project.model.js
modules/projects/server/routes/project.routes.js
scripts/mmti-hookup/setup.sh
scripts/mmti-hookup/update-major-mines.js

This adds fields required by MMTI to the Project collection. It also provides a new API call to retrieve major mines.
**Note**: This includes a script which must be run after landing. This populates the new Project fields with data from MMTI, and provides a relationship between MEM and EPIC projects. The script is not time-sensitive; I will run it when appropriate.

MEM-453 Project model update and script for MMTI hook-up

---

modules/collections/client/directives/collections.directives.js
modules/documents/client/directives/documents.manager.directive.js
modules/documents/client/views/document-manager.html

MEM-482 Collections - Refresh document info panel upon adding collections

---

modules/documents/client/components/doc-categories/doc-categories.js

+  the extra additions/deletions are for some formatting fixes for the variable mainCategories. The actual code added is only the category "dangerous occurrences")

MEM-484: Add new Document Category: Dangerous Occurrences

---

modules/core/client/scss/components/file-browser.scss
modules/core/server/controllers/core.dbmodel.controller.js
modules/documents/client/directives/documents.manager.directive.js
modules/documents/client/directives/documents.manager.move.directive.js
modules/documents/client/views/document-manager-move.html
modules/documents/server/controllers/core.document.controller.js
modules/projects/server/controllers/project.controller.js

Porting code for related: 
EPIC-1155 Tweaks and EPIC-1231 as well.

MEM-437 Document Manager - block move of published docs or folders into Unpublished folders

---

package.json

Also, add `npm run build` task to `package.json`

NOBUG: fix global GIT configuration in `package.json`

---

modules/projects/client/views/project-partials/project.entry.html

Removing old ownership information from project edit screen

MEM-560: Edit Project Owners and Owners Percentage.

---

modules/core/client/scss/global/layout.scss

Fixing Duplicated Style Properties

---

modules/core/client/scss/global/footer.scss
modules/core/client/scss/global/header.scss
modules/core/client/scss/global/layout.scss
modules/core/client/scss/themes/default.scss
modules/core/client/views/footer.client.view.html
modules/core/client/views/header.client.view.html
modules/core/client/views/menu.client.view.html
modules/users/client/scss/users.scss

Updated header and footer components with new markup/styling
Additional Fixes
- Fixed a small positioning issue in the Roles & Permissions interface
- Cleaned up some spacing issues in the side navigation menu and removed the 'map pin' icon from the project title.
- Some clean-up on the default style sheet.

[MEM-591] Update Header / Footer Components

---

gruntfile.js
modules/core/client/app/constants.js
modules/projects/client/config/project.client.routes.js
modules/projects/client/controllers/project.client.controllers.js
modules/projects/client/scss/edit-project-form.scss
modules/projects/client/views/project-partials/edit-public-content.html
modules/projects/client/views/project-partials/project.detail.html
modules/projects/client/views/project-partials/project.entry.html
modules/projects/server/models/project.model.js
modules/projects/server/routes/project.routes.js
scripts/public-content/update-mines.js

This requires an ETL to be run after deployment.
MEM-595 must be deployed on MMTI when this is deployed on MEM.

MEM-559 Edit MMTI Tab Content in MEM. MEM-584 Site Activities. ETL.

---

modules/documents/client/directives/documents.manager.directive.js

Also removed the additional self.deleteDocument function, not sure why it was duplicated.

MEM-597: Deleting a document does not update its associated collections

---

modules/core/client/config/core.client.menus.js
modules/core/client/scss/components/forms.scss
modules/core/client/scss/global/header.scss
modules/core/client/views/menu.client.view.html
modules/projects/client/scss/edit-project-form.scss
modules/projects/client/views/project-partials/edit-public-content.html
modules/projects/client/views/project-partials/project.entry.html

Removed access to unused functionality.
- Cleaned up a few issues with the fieldset/legend selectors
- Cleaned up some styling code for the Edit Project Forms (both Project Meta & Project Public Content)
- Removed unused functionality/markup from the Edit Project Form.

[MEM-590] Removing Navigation to Unused Functionality

---

modules/core/client/scss/components/forms.scss
modules/core/client/scss/core.scss
modules/projects/client/controllers/project.client.controllers.js
modules/projects/client/scss/edit-external-links.scss
modules/projects/client/views/project-partials/edit-external-links-modal.html
modules/projects/client/views/project-partials/edit-public-content.html

* Setup UI
* Setup new client-side routes
* Implement client-side logic to add, remove and update external links
* Reset list order after an external link is removed

MEM-558 Edit External Links of a Project - MMTI

---

modules/core/client/views/footer.client.view.html

Removing 'Contact' page link at stakeholder request (current content includes information not related to MEM).

[MEM-590-Fix] Removing Contact Link from Footer

---

modules/projects/client/controllers/project.client.controllers.js
modules/projects/client/directives/external.links.reorder.directives.js
modules/projects/client/views/project-partials/edit-public-content.html
modules/projects/client/views/project-partials/reorder-external-links-content.html
modules/projects/client/views/project-partials/reorder-external-links-modal.html

* Add modal, `x-reorder-external-links-modal` directive to reorder links

MEM-585 Allow Reordering of External Links for a Project - MMTI

---

modules/projects/client/config/project.client.routes.js
modules/projects/client/controllers/project.client.controllers.js
modules/projects/client/controllers/projects.client.controllers.js
modules/projects/client/services/project.model.service.js
modules/projects/client/views/project-partials/edit-public-content.html
modules/projects/client/views/project-partials/project.entry.html
modules/projects/client/views/projects-partials/projects-list.html
modules/projects/server/controllers/project.controller.js
modules/projects/server/models/project.model.js
modules/projects/server/routes/project.routes.js

- save public content without validation (remembers tab!)
- added 'promote to mines.nrs' button to public content page
- added 'Are you sure?' and validation to promotion
- added 'displayed on mines.nrs' column to projects list (and fixed filtering across the board)

MEM-596 Promote project to mines.nrs

---

package.json

updates to:
- node
- npm
- acl
- async
- body-parser
- bower

Slow rollout of changes part 1

---

package.json

all the dev dependencies except grunt

Slow rollout of changes part 6: dev dependencies

---

bower.json
config/assets/default.js
config/assets/production.js
modules/core/client/app/config.js
modules/utils/client/tinymce/tinymce.js

Note to devs: This update will require you to blow away `/public/lib/angular-ui-tinymce` and `/public/lib/tinymce` and then run `yarn`.

MEM-623 Added custom ui-tinymce directive to project

---

modules/users/client/controllers/authentication.client.controller.js

EM-96 Ensure global user data is loaded at login time.

---

scripts/users/add-permissions.js
scripts/users/setup.sh

Missed some when Collections and Public Content were added.

EM-79 ETL to add sysadmin permissions.

---

modules/core/client/app/init.js
package.json
yarn.lock

Added event handler to cancel/close modal windows when navigating away from the current page.
Also bumped mongoose to 4.13.8 to fix unhandled promise rejection issue.

EM-41: Close modals when navigating away from the current page.

---

modules/documents/client/directives/documents.manager.add.directive.js
modules/documents/client/directives/documents.manager.edit.directive.js
modules/documents/client/directives/documents.manager.rename.directive.js
modules/documents/client/views/document-manager-edit.html

> Document manager naming does not account for case sensitivity
- Altered add and batch-rename functionality to account for case sensitivity
- Refactored in-line edit property to use new modal in-line alert protocol, altered functionality to account for case-sensitivity
- Fixed whitespace for involved files, homogenized code format between esm-server and mem-admin

EM-288 fix for MEM

---

modules/project-comments/client/services/comment.model.service.js
sonar-runner/build.gradle

@RandyInVictoria
The file change is, yet again, a non UTF-8 file for which I changed the encoding (not sure how it got there, but SonarQube was flagging it).

Updated SonarQube configuration to use better build names.

---

modules/core/client/app/constants.js
modules/core/client/config/core.client.menus.js
modules/core/client/directives/show-errors.client.directives.js
modules/core/client/scss/components/buttons.scss
modules/core/client/scss/components/forms.scss
modules/core/client/scss/components/ng-table-overrides.scss
modules/core/client/scss/components/table.scss
modules/core/client/scss/components/tabs.scss
modules/core/client/scss/global/layout.scss
modules/core/client/scss/themes/default.scss
modules/organizations/client/views/org-search-chooser.html
modules/projects/client/config/project.client.routes.js
modules/projects/client/controllers/project.client.controllers.js
modules/projects/client/directives/project.client.directives.js
modules/projects/client/scss/edit-external-links.scss
modules/projects/client/scss/edit-project-form.scss
modules/projects/client/scss/edit-project-site-activities.scss
modules/projects/client/views/project-partials/edit-external-links-modal.html
modules/projects/client/views/project-partials/project-tombstone.html
modules/projects/client/views/project-partials/project.detail.html
modules/projects/client/views/project-partials/project.entry.html

This is a ton of work from https://github.com/jeznorth/mem-admin/tree/EM-143 with some bits and pieces tied together by me. It will need to go back to Jer for testing and styling.

EM-9 EM-143 Edit Project changes (public content, save, publish)

---

modules/core/client/scss/components/forms.scss
modules/projects/client/controllers/project.client.controllers.js
modules/projects/client/views/project-partials/project.entry.html
modules/projects/server/controllers/project.controller.js
modules/utils/client/views/partials/modal-confirm-generic.html

- Some minor interface updates / clean-up issues with the project edit screens
- added last modified by field to the project edit screen (EM-247)

[EM-9] [EM-247] UI Clean-up

---

modules/collections/client/controllers/collections.controllers.js
modules/collections/client/views/collection-edit.html
modules/core/client/app/init.js
modules/core/client/directives/core.client.alert.directive.js

- AlertService errors now standardized throughout collections
- Credit to @esune for allowing alerts to persist through route changes

EM-218 fix for MEM (collections alerts)

---

modules/core/client/directives/menu.client.directives.js
modules/core/client/views/menu.client.view.html

When using the side navbar and navigating to an item, that item is now highlighted in the side navbar

em-114 make active tab highlighted in side nav bar

---

modules/projects/server/controllers/project.controller.js

Ported change from EPIC to MEM.
Allow adding of same named directory at different depth in file directory:
A1 >A2
A2

em-172 able to add same named directory at different depth

---

modules/collections/client/controllers/collections.controllers.js
modules/collections/client/views/collection-edit.html

Modified the collections controller and view to leverage dateAdded, as addedBy sometimes resolves to null, such as when a user has been deleted from the database. This was causing unspecified behaviour.

EM-647-hotfix

---

Jenkinsfile
Jenkinsfile.dev
zap/README.md
zap/runzap.sh

The Jenkinsfile(s) have been updated to match what is already in place in *esm-server*.
The main notable differences are:
- changed how secrets are handled for _build_ and _deploy_ steps: now using the (much faster) _master_ executor on Jenkins, rather than waiting for dynamically create pods.
- temporarily disabled Functional Test step: the new changes for fixture-based tests we made require updates to the jenkins slave image and further tweaks to the build process, new JIRA issue will be created to handle this.

EM-623: Updated jenkinsfiles for new pipeline automation.

---

modules/collections/client/controllers/collections.controllers.js
modules/collections/client/views/collection-edit.html
modules/documents/client/directives/documents.manager.link.directive.js
modules/documents/client/views/document-manager-link.html

- Modal modified to create new list with every invocation
- Changed text to reflect 'Selected Documents' instead of 'Linked Documents'

EM-564: Collections - Link Document Interface Renders all documents that are already linked.

---

modules/core/client/scss/components/tabs.scss
modules/projects/client/views/project-partials/project.entry.html

Minor Markup/Styling Cleanup 
- Tightened up spacing for tab contents on viewports ~1366px
- Fixed the meta container for the (project.entry.html)
- Added published/unpublished tags (project.entry.html)
- Added title tags for form buttons (project.entry.html)

[UI-Fix] Fixing markup and styling inconsistencies

---

modules/projects/client/config/project.client.routes.js

Bugfix - Remove unused controller parameter.

Bugfix - Remove unused controller parameter.

---

modules/projects/client/config/project.client.routes.js

bugfix - remove unused variable

bugfix - remove unused variable

---

modules/collections/client/controllers/collections.controllers.js

Needed to call the appropriate mongoose API when creating a brand new object...

EM-140-bugfix: Fixed issue that prevented new collections from being created.

---

modules/core/server/controllers/core.minio.controller.js
modules/documents/server/routes/core.document.routes.js
scripts/minio/README.md
yarn.lock

The change should address the out-of-memory issues observed when uploading large files.
Now using disk-based multer file uploads, instead of in-memory file streaming.

Bigfile upload fix

---

Jenkinsfile.dev

We will enable if this works in esm-server

EM-1341: update bddstack image
